services:
  mariadb:
    container_name: mariadb
    init: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - .env
    build: requirements/mariadb
    pull_policy: build
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker-network
    image: mariadb
  nginx:
    container_name: nginx
    init: true
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    build: requirements/nginx
    pull_policy: build
    ports:
      - "80:80"   # HTTP - not an entry point, just a redirect to https
      - "443:443" # HTTPS - sole secure entry point
    volumes:
      - wordpress:/var/www/html
      - static-site:/usr/share/nginx/html
    networks:
      - docker-network
    depends_on:
      - wordpress
      - mariadb
      - static-site
    image: nginx
  wordpress:
    container_name: wordpress
    init: true
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: requirements/wordpress
    pull_policy: build
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    depends_on:
      - mariadb
      - redis
    image: wordpress
  redis:
    build: ./requirements/bonus/redis
    pull_policy: build
    container_name: redis
    restart: always
    networks:
      - docker-network
    image: redis
  ftp:
    build: ./requirements/bonus/ftp
    pull_policy: build
    container_name: ftp
    restart: always
    env_file:
      - .env
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - WORDPRESS_DIR=${WORDPRESS_DIR}
    volumes:
      - wordpress:/var/www/html
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - docker-network
    depends_on:
      - wordpress
    image: ftp
  adminer:
    build: ./requirements/bonus/adminer
    pull_policy: build
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - docker-network
    image: adminer
  static-site:
    container_name: static-site
    build: ./requirements/bonus/static-site
    pull_policy: build
    restart: always
    volumes:
      - static-site:/usr/share/nginx/html
    networks:
      - docker-network
    image: static-site
  portainer:
    build: ./requirements/bonus/portainer
    pull_policy: build
    container_name: portainer
    ports:
      - "9000:9000"
    networks:
      - docker-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    image: portainer
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  portainer:
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/portainer
  static-site:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/static-site

networks:
  docker-network:
    name: docker-network
    driver: bridge